#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${DATASTORE_PROJECT_ID}" ]]; then
  echo "Missing DATASTORE_PROJECT_ID environment variable" >&2
  exit 1
fi

if [[ -z "${DATASTORE_LISTEN_PORT}" ]]; then
  echo "Missing DATASTORE_LISTEN_PORT environment variable" >&2
  exit 1
fi

options=""

if [[ -n "${CONSISTENCY}" ]]; then
  options="$options --consistency=${CONSISTENCY}"
fi

if [[ "${STORE_ON_DISK}" == "true" ]]; then
  options="$options --store-on-disk --data-dir=/opt/data"
else
  options="$options --no-store-on-disk"
fi

# Config gcloud project
gcloud config set project ${DATASTORE_PROJECT_ID}

echo "Starting datastore emulator with the following options: '$options'"

# Start emulator
gcloud beta emulators datastore start \
  --host-port=0.0.0.0:${DATASTORE_LISTEN_PORT} \
  ${options}
